/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245_project1.screens;

import cs245_project1.controller.ButtonListener;
import cs245_project1.view.HighScorePanel;
import cs245_project1.view.MainScreen;
import java.awt.FlowLayout;
import javax.swing.JFrame;

/**
 *
 * @author Brian
 */
public class MainFrame extends JFrame {
    static GameScreen startScreen;
    private MainScreen mainScreen;
    private HighScorePanel highScorePanel;
    private CreditsScreen creditsScreen;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        super("Hangman");
        setLayout(new FlowLayout());
        highScorePanel = new HighScorePanel();
        mainScreen = new MainScreen();
        creditsScreen = new CreditsScreen();
        setContentPane(mainScreen);
        setSize(600,400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        highScorePanel.setButtonListener(new ButtonListener(){
            public void btnClicked(String name){
                if (name.equals("Back")){
                    setContentPane(mainScreen);
                    invalidate();
                    validate();
                }
            }
        });
        mainScreen.setButtonListener(new ButtonListener(){
            public void btnClicked(String name){
                if (name.equals("Play")){
                    startScreen = new GameScreen();
                    dispose();
                }
                else if (name.equals("High")){
                    setContentPane(highScorePanel);
                    invalidate();
                    validate();
                }
                else if (name.equals("Credit")){
                    setContentPane(creditsScreen);
                    invalidate();
                    validate();
                }
            }
        });
        creditsScreen.setButtonListener(new ButtonListener(){
            public void btnClicked(String name){
                if (name.equals("Back")){
                    setContentPane(mainScreen);
                    invalidate();
                    validate();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
