/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs245_project1.view;

import cs245_project1.controller.ButtonListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/***************************************************************
* file: HighScorePanel.java
* author: Brian Van Hooser
* class: CS 245 - Intro to GUI
*
* assignment: Project 1 (Hangman)
* date last modified: 10/6/2016
*
* purpose: This is the Panel that provides the list of high scores.
* This list is currently static, but will later be adjusted for
* actual data.
*
****************************************************************/

public class HighScorePanel extends JPanel implements ActionListener {
    
    private ButtonListener btnListener;
    /**
     * Creates new form HighScorePanel
     */
    
    // Method: HighScorePanel
    // Purpose: This is the constructor that calls the generated code 
    // for the Panel content, and then adds a listener to the button.
    
    public HighScorePanel() {
        initComponents();
        backButton.addActionListener(this);
    }
    
    // Method: setButtonListener
    // Purpose: This method is to allow the passing of the correct implementation
    // of the ButtonListener interface. This assists in correctly switching panels
    // within the one MainFrame class.
    
    public void setButtonListener(ButtonListener listener){
        this.btnListener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JTextField();
        highScore1 = new javax.swing.JTextField();
        highScore2 = new javax.swing.JTextField();
        highScore4 = new javax.swing.JTextField();
        highScore3 = new javax.swing.JTextField();
        highScore5 = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        Header.setEditable(false);
        Header.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Header.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Header.setText("High Scores");
        Header.setBorder(null);

        highScore1.setEditable(false);
        highScore1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        highScore1.setText("PL1...100");
        highScore1.setBorder(null);

        highScore2.setEditable(false);
        highScore2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        highScore2.setText("PL2...100");
        highScore2.setBorder(null);

        highScore4.setEditable(false);
        highScore4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        highScore4.setText("PL4...100");
        highScore4.setBorder(null);

        highScore3.setEditable(false);
        highScore3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        highScore3.setText("PL3...100");
        highScore3.setBorder(null);

        highScore5.setEditable(false);
        highScore5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        highScore5.setText("PL5...100");
        highScore5.setBorder(null);

        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 535, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Header)
                            .addComponent(highScore3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(highScore4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(highScore5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(highScore1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(highScore2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(210, 210, 210))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(highScore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(highScore2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(highScore3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highScore4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(highScore5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Header;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField highScore1;
    private javax.swing.JTextField highScore2;
    private javax.swing.JTextField highScore3;
    private javax.swing.JTextField highScore4;
    private javax.swing.JTextField highScore5;
    // End of variables declaration//GEN-END:variables

    @Override
    
    // Method: actionPerformed
    // Purpose: This method handled the scenario where a button 
    // is clicked. This returns a set string depending on which 
    // button ends up being clicked.
    
    public void actionPerformed(ActionEvent e) {
        JButton clicked = (JButton) e.getSource();
        
        if (clicked == backButton)
            if (btnListener != null)
                btnListener.btnClicked("Back");
    }
}
